/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Assign Httponly Cookie
         * @description Logs in a user and returns an http_only cookie.
         */
        post: operations["assign_httponly_cookie_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register User
         * @description Register New user
         */
        post: operations["register_user_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout User
         * @description Logs out a user by clearing the http_only cookie.
         */
        post: operations["logout_user_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Auth Status
         * @description Endpoint to check authentication status.
         */
        get: operations["auth_status_api_v1_auth_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/textbooks/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Textbooks
         * @description Get all available textbooks to the user.
         */
        get: operations["get_textbooks_api_v1_textbooks_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/textbooks/{textbook_uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Textbook Details
         * @description Get metadata for a specific textbook.
         */
        get: operations["get_textbook_details_api_v1_textbooks__textbook_uuid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/textbooks/{textbook_uuid}/chapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Chapters
         * @description Get available chapters for a textbook.
         *     and returns a consistent response shape: { "chapters": [...] }.
         */
        get: operations["get_chapters_api_v1_textbooks__textbook_uuid__chapters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/textbooks/{textbook_uuid}/chapters/{chapter_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Chapter Pdf
         * @description Return a presigned URL to the chapter PDF stored in S3.
         */
        get: operations["get_chapter_pdf_api_v1_textbooks__textbook_uuid__chapters__chapter_id__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/textbooks/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Textbook To User
         * @description Add a textbook to the user's library by textbook code.
         */
        post: operations["add_textbook_to_user_api_v1_textbooks_add_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quiz/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Quiz
         * @description Generate quiz from textbook chapter context using LLM.
         *
         *     Request Body:
         *     - textbook_id: The ID of the textbook
         *     - chapter: The chapter of the textbook to generate the quiz for
         *     - num_questions: The number of questions to generate for the quiz
         */
        post: operations["generate_quiz_api_v1_quiz_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quiz/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List User Quizzes
         * @description List all quizzes for the current user.
         *
         *     user is obtained from the validated cookie token.
         */
        get: operations["list_user_quizzes_api_v1_quiz_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quiz/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Quiz
         * @description Get a specific quiz for the current user by id.
         */
        get: operations["get_user_quiz_api_v1_quiz__item_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete User Quiz
         * @description Delete a specific quiz for the current user.
         */
        delete: operations["delete_user_quiz_api_v1_quiz__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddTextbookRequest */
        AddTextbookRequest: {
            /** Code */
            code: string;
        };
        /** Book */
        Book: {
            textbookInfo: components["schemas"]["Textbook"];
            userProgress?: components["schemas"]["BookProgress"] | null;
        };
        /** BookProgress */
        BookProgress: {
            /**
             * Last Read Page
             * @description The last page the user read
             */
            last_read_page: number;
            /**
             * Chapters
             * @description Mapping of chapter indices to percentage done of chapter
             */
            chapters: {
                [key: string]: number;
            };
            /**
             * Last Visited Chapter
             * @description Last visited chapter index
             */
            last_visited_chapter: number;
            /**
             * Last Visited Page
             * @description Last visited page within the chapter
             */
            last_visited_page: number;
        };
        /** Chapter */
        Chapter: {
            /**
             * Id
             * @description Identifier for the chapter
             */
            id: number;
            /**
             * Title
             * @description Title of the chapter
             */
            title: string;
            /**
             * File
             * @description File associated with the chapter
             */
            file: string;
            /**
             * Start Page
             * @description Starting page number of the chapter
             */
            start_page: number;
            /**
             * Sections
             * @description List of sections within the chapter
             */
            sections: components["schemas"]["Section"][];
        };
        /** ChapterPDFResponse */
        ChapterPDFResponse: {
            /** Pdf Url */
            pdf_url: string;
            /** Chapter Id */
            chapter_id: string;
        };
        /** DeleteResponse */
        DeleteResponse: {
            /**
             * Ok
             * @description Indicates if the deletion was successful
             */
            ok: boolean;
        };
        /** GenerateRequest */
        GenerateRequest: {
            /**
             * Context
             * @description The context from the textbook chapter to generate the quiz from
             */
            context: string;
            /**
             * Textbook Id
             * @description The ID of the textbook
             */
            textbook_id: string;
            /**
             * Chapter
             * @description The chapter of the textbook to generate the quiz for
             */
            chapter: number;
            /**
             * Num Questions
             * @description The number of questions to generate for the quiz
             * @default 5
             */
            num_questions: number;
        };
        /** GeneratedQuiz */
        GeneratedQuiz: {
            /**
             * Questions
             * @description A list of quiz questions
             */
            questions: components["schemas"]["QuizQuestion"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /**
             * Message
             * @default Login successful
             */
            message: string;
            /**
             * Set Cookie
             * @default access_token=<token>; HttpOnly; Secure; SameSite=Lax
             */
            set_cookie: string | null;
        };
        /** LogoutResponse */
        LogoutResponse: {
            /**
             * Message
             * @default Successfully logged out
             */
            message: string;
        };
        /** @example 5eb7cf5a86d9755df3a6c593 */
        PydanticObjectId: string;
        /** QuizItem */
        QuizItem: {
            /**
             * Id
             * @description Unique identifier for the quiz
             */
            id: string;
            /**
             * User
             * @description ID of the user who owns the quiz
             */
            user: string;
            /**
             * Quiz
             * @description Quiz questions list
             */
            quiz: components["schemas"]["QuizQuestion"][];
            /**
             * Created Time
             * @description Timestamp when the quiz was created
             */
            created_time: number;
            /**
             * Hint
             * @description Optional hint or section focus for the quiz
             */
            hint: string | null;
            /**
             * Quiz Result
             * @description Results of the quiz taken by the user
             */
            quiz_result: {
                [key: string]: unknown;
            };
        };
        /** QuizQuestion */
        QuizQuestion: {
            /**
             * Question
             * @description The question to be answered
             */
            question: string;
            /**
             * Choices
             * @description Four multiple choice options for the question
             */
            choices: string[];
            /**
             * Answer
             * @description The index of the correct answer (0th index is the first option)
             */
            answer: number;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Username */
            username: string;
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** RegisterResponse */
        RegisterResponse: {
            /** Id */
            id: string;
            /** Username */
            username: string;
            /**
             * Message
             * @default User registered successfully
             */
            message: string;
        };
        /** Section */
        Section: {
            /**
             * Title
             * @description Title of the section
             */
            title: string;
            /**
             * Page Offset
             * @description Page offset in the pdf
             */
            page_offset: number;
        };
        /** StatusResponse */
        StatusResponse: {
            /** Is Authenticated */
            is_authenticated: boolean;
            /** User Uuid */
            user_uuid: string;
        };
        /** Textbook */
        Textbook: {
            /** @description MongoDB document ObjectID */
            _id?: components["schemas"]["PydanticObjectId"] | null;
            /**
             * Author
             * @description Author of the textbook
             */
            author: string;
            /**
             * Title
             * @description Title of the textbook
             */
            title: string;
            /**
             * Subject
             * @description Subject of the textbook
             */
            subject: string;
            /**
             * Code
             * @description Code of the textbook
             */
            code: string;
            /**
             * Chapters
             * @description List of chapters in the textbook
             */
            chapters: components["schemas"]["Chapter"][];
            /**
             * Cover Url
             * @description URL of the textbook cover image
             */
            cover_url: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    assign_httponly_cookie_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_user_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_user_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
        };
    };
    auth_status_api_v1_auth_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    get_textbooks_api_v1_textbooks_list_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Book"][];
                };
            };
        };
    };
    get_textbook_details_api_v1_textbooks__textbook_uuid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                textbook_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Textbook"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chapters_api_v1_textbooks__textbook_uuid__chapters_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                textbook_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chapter"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chapter_pdf_api_v1_textbooks__textbook_uuid__chapters__chapter_id__pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                textbook_uuid: string;
                chapter_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterPDFResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_textbook_to_user_api_v1_textbooks_add_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddTextbookRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_quiz_api_v1_quiz_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratedQuiz"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_user_quizzes_api_v1_quiz_list_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizItem"][];
                };
            };
        };
    };
    get_user_quiz_api_v1_quiz__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_quiz_api_v1_quiz__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
